// Code generated by "stringer -type=Channel -linecomment=true"; DO NOT EDIT.

package dl

import "strconv"

const (
	_Channel_name_0 = "Run InformationRun Status"
	_Channel_name_1 = "New Sector TimeLap MarkerLogger StorageGPS Time StorageAccelerationsTimestampGPS PositionSpeed DataBeacon Pulse"
	_Channel_name_2 = "Frequency 1Frequency 2Frequency 3Frequency 4Frequency 5"
	_Channel_name_3 = "Analog 1Analog 2Analog 3Analog 4Analog 5Analog 6Analog 7Analog 8Analog 9Analog 10Analog 11Analog 12Analog 13Analog 14Analog 15Analog 16Analog 17Analog 18Analog 19Analog 20Analog 21Analog 22Analog 23Analog 24Analog 25Analog 26Analog 27Analog 28Analog 29Analog 30Analog 31Analog 32Channel DataDisplay DataReflashData StorageCourse DataGPS AltitudeExtended Frequency 1Extended Frequency 2Extended Frequency 3Extended Frequency 4Extended RPMStart RunProcessed Speed DataGear Setup DataBargraph Setup DataDashboard Setup Data 1Dashboard Setup Data 2New Target Sector TimeNew Target Marker TimeAuxillery Input Module NumberExternal TemperatureExternal FrequencyExternal PercentageExternal TimeNew LCD DataNew LED DataPre-Calculated Distance DataYaw RatesCalculated YawPitch RatePitch AngleRoll RateRoll AngleGradientPulse Count 1Pulse Count 2Pulse Count 3Pulse Count 4BaselineUnit ControlZ AccelerationExternal AngleExternal PressureExternal Misc"
	_Channel_name_4 = "Sector Definition"
	_Channel_name_5 = "DVC CommunicationsVideo Frame Index"
)

var (
	_Channel_index_0 = [...]uint8{0, 15, 25}
	_Channel_index_1 = [...]uint8{0, 15, 25, 39, 55, 68, 77, 89, 99, 111}
	_Channel_index_2 = [...]uint8{0, 11, 22, 33, 44, 55}
	_Channel_index_3 = [...]uint16{0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 81, 90, 99, 108, 117, 126, 135, 144, 153, 162, 171, 180, 189, 198, 207, 216, 225, 234, 243, 252, 261, 270, 279, 291, 303, 310, 322, 333, 345, 365, 385, 405, 425, 437, 446, 466, 481, 500, 522, 544, 566, 588, 617, 637, 655, 674, 687, 699, 711, 739, 748, 762, 772, 783, 792, 802, 810, 823, 836, 849, 862, 870, 882, 896, 910, 927, 940}
	_Channel_index_5 = [...]uint8{0, 18, 35}
)

func (i Channel) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Channel_name_0[_Channel_index_0[i]:_Channel_index_0[i+1]]
	case 4 <= i && i <= 12:
		i -= 4
		return _Channel_name_1[_Channel_index_1[i]:_Channel_index_1[i+1]]
	case 14 <= i && i <= 18:
		i -= 14
		return _Channel_name_2[_Channel_index_2[i]:_Channel_index_2[i+1]]
	case 20 <= i && i <= 95:
		i -= 20
		return _Channel_name_3[_Channel_index_3[i]:_Channel_index_3[i+1]]
	case i == 101:
		return _Channel_name_4
	case 103 <= i && i <= 104:
		i -= 103
		return _Channel_name_5[_Channel_index_5[i]:_Channel_index_5[i+1]]
	default:
		return "Channel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
